% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={hw1code},
  pdfauthor={Han-Yuan Hsu},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{hw1code}
\author{Han-Yuan Hsu}
\date{2022-09-09}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{111}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\#3 Download the dataset on the annual size of the Resident Population
of California from \url{https://fred.stlouisfed.org/series/CAPOP}. This
dataset gives the annual population of California from 1900 to 2021
(units are in thousands of persons and there is no seasonal adjustment
to this data). The goal of this exercise is to fit the linear trend
model (1) to this dataset.

Note the unit for CAPOP is thousands of persons.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}CAPOP.csv\textquotesingle{}}\NormalTok{)}
\FunctionTok{head}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         DATE CAPOP
## 1 1900-01-01  1490
## 2 1901-01-01  1550
## 3 1902-01-01  1623
## 4 1903-01-01  1702
## 5 1904-01-01  1792
## 6 1905-01-01  1893
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{=} \FunctionTok{length}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{DATE) }\CommentTok{\# number of timepoints, 122}
\end{Highlighting}
\end{Shaded}

\hypertarget{a}{%
\subsection{a}\label{a}}

Provide point estimates for β0, β1 along with appropriate uncertainty
intervals. Interpret your point estimates and explain why they make
sense. (4 points)

Our model is \(Y_i = \beta_0 + \beta_1 t_i + Z_i\). The point estimates
of \(\beta_0\) and \(\beta_1\) are \(\hat\beta_0\) and \(\hat\beta_1\),
which are obtained from the lm function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\NormalTok{n}
\NormalTok{lin }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{CAPOP }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ t)}
\FunctionTok{summary}\NormalTok{(lin)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = df$CAPOP ~ 1 + t)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3519.8 -1456.6  -209.5  1629.5  5488.0 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -4357.912    395.791  -11.01   <2e-16 ***
## t             359.874      5.585   64.44   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2172 on 120 degrees of freedom
## Multiple R-squared:  0.9719, Adjusted R-squared:  0.9717 
## F-statistic:  4152 on 1 and 120 DF,  p-value: < 2.2e-16
\end{verbatim}

From the summary, we see that \(\hat\beta_0\) is -4357.912 and
\(\hat\beta_1\) is 359.874. The negative intercept may be frowned upon
because the predicted population of the first timepoint (t=1) will be
-4357.912 + 359.874, which is negative and so does not make sense. But
the regression line does capture the long-term increasing trend of the
population, which is shown by a positive \(\hat\beta_1\).

\#\#b Along with a plot of the observed dataset, plot lines
corresponding to 30 samples from the posterior distribution of (β0, β1).
Comment on the range of uncertainty revealed in this plot. (4 points)

From lecture, we know the posterior (β0, β1) follows
\[t_{n-2}\big(\hat\beta, \; \frac{S(\hat\beta)}{n-2}(X'X)^{-1}\big).\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta\_hat }\OtherTok{=} \FunctionTok{as.vector}\NormalTok{(lin}\SpecialCharTok{$}\NormalTok{coefficients)}
\NormalTok{S }\OtherTok{=} \FunctionTok{sum}\NormalTok{(lin}\SpecialCharTok{$}\NormalTok{residuals}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\CommentTok{\# residual sum of squares}
\NormalTok{X }\OtherTok{=} \FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, n), t))}
\NormalTok{Sigma }\OtherTok{=}\NormalTok{ S }\SpecialCharTok{/}\NormalTok{ (n}\DecValTok{{-}2}\NormalTok{) }\SpecialCharTok{*} \FunctionTok{solve}\NormalTok{(}\FunctionTok{t}\NormalTok{(X) }\SpecialCharTok{\%*\%}\NormalTok{ X)}
\end{Highlighting}
\end{Shaded}

The following function gives you N independent samples from the
multivariate t distribution with specified mu, Sigma, and df (degrees of
freedom):

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(mvtnorm)}
\NormalTok{get\_random\_t }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(N, mu, Sigma, df) \{}
  \CommentTok{\# get N samples}
  \CommentTok{\#d = length(mu) \# dimension}
  \FunctionTok{rbind}\NormalTok{(mu)[}\FunctionTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, N), ] }\SpecialCharTok{+} \FunctionTok{rmvnorm}\NormalTok{(N, }\AttributeTok{sigma =}\NormalTok{ Sigma)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{rchisq}\NormalTok{(N, }\AttributeTok{df =}\NormalTok{ df)}\SpecialCharTok{/}\NormalTok{df)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Plot:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(t, df}\SpecialCharTok{$}\NormalTok{CAPOP, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{)}
\NormalTok{t30 }\OtherTok{\textless{}{-}} \FunctionTok{get\_random\_t}\NormalTok{(}\AttributeTok{N=}\DecValTok{30}\NormalTok{, }\AttributeTok{mu=}\NormalTok{beta\_hat, }\AttributeTok{Sigma=}\NormalTok{Sigma, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{)}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{30}\NormalTok{) \{}
  \FunctionTok{abline}\NormalTok{(}\AttributeTok{a=}\NormalTok{t30[i,}\DecValTok{1}\NormalTok{], }\AttributeTok{b=}\NormalTok{t30[i,}\DecValTok{2}\NormalTok{], }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-7-1.pdf} The
uncertainty of the fitted lines look pretty small. The reason is as
follows: from the Sigma matrix,

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Sigma}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                        t
##   156650.475 -1918.16909
## t  -1918.169    31.18974
\end{verbatim}

we know that \(\beta_0\) follows the t distribution
\(t_{n-2}(\hat\beta_0, 156650.475)\). Since the distribution is close to
normal, it is unlikely that \(\beta_0\) will lie outside of the 2-sd
interval
\([\hat\beta_0 - 2\sqrt{156650},\; \hat\beta_0 + 2\sqrt{156650}] = [\hat\beta_0 - 791.5, \; \hat\beta_0 + 791.5]\).
But \(\hat\beta_0\) is -4357.9, so 791.5 is small compared with
\(\hat\beta_0\). The same reasoning works for \(\beta_1\), and I expect
its confidence interval is even tighter because 31.18974 is way smaller.

\#\#c Using the results of Problem 2, provide a point estimate along
with appropriate uncertainty quantification of the Resident Annual
Population of California for the year 2025. Comment on whether your
answer makes intuitive sense. (5 points)

Year 2025 corresponds to the following timepoint:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{time\_point }\OtherTok{=}\NormalTok{ (}\DecValTok{2025} \SpecialCharTok{{-}} \DecValTok{2021}\NormalTok{) }\SpecialCharTok{+}\NormalTok{ n}
\end{Highlighting}
\end{Shaded}

From problem 2, we know that the population at \texttt{time\_point},
conditioned on data of past population values, follows the t
distribution \(t_{n-2}(\text{mu}, \,\text{scale}^2)\), where mu and
scale are as given in the code block below:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mu }\OtherTok{=}\NormalTok{ beta\_hat[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+}\NormalTok{ beta\_hat[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{*}\NormalTok{ time\_point}
\NormalTok{sigma\_hat\_squared }\OtherTok{=}\NormalTok{ S }\SpecialCharTok{/}\NormalTok{ (n}\DecValTok{{-}2}\NormalTok{)}
\NormalTok{time\_point\_mat }\OtherTok{=} \FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, time\_point))}
\NormalTok{scale }\OtherTok{=} \FunctionTok{sqrt}\NormalTok{(sigma\_hat\_squared }\SpecialCharTok{+} \FunctionTok{t}\NormalTok{(time\_point\_mat) }\SpecialCharTok{\%*\%}\NormalTok{ Sigma }\SpecialCharTok{\%*\%}\NormalTok{ time\_point\_mat)}
\end{Highlighting}
\end{Shaded}

Thus, the predicted population is just mu.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mu}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 40986.16
\end{verbatim}

Let \(Y_{n+1}\) be the population at \texttt{time\_point}. Then
\[\frac{Y_{n+1} - \text{mu}}{\text{scale}},\] again conditioned on past
data, follows the standard t distribution with n-2 degrees of freedom,
so we can calculate the 95\% confidence interval.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{c}\NormalTok{(mu }\SpecialCharTok{+}\NormalTok{ scale}\SpecialCharTok{*}\FunctionTok{qt}\NormalTok{(}\AttributeTok{p=}\NormalTok{.}\DecValTok{025}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{), mu }\SpecialCharTok{+}\NormalTok{ scale}\SpecialCharTok{*}\FunctionTok{qt}\NormalTok{(}\AttributeTok{p=}\NormalTok{.}\DecValTok{975}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 36608.87 45363.46
\end{verbatim}

The confidence interval makes sense to me; I expect the uncertainty of a
new prediction to be larger, and indeed, the scale is slightly larger
than sigma\_hat, as shown below:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{as.vector}\NormalTok{(scale)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2210.831
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sqrt}\NormalTok{(sigma\_hat\_squared)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2172.403
\end{verbatim}

\#\#d Discuss the appropriateness of the linear trend model for this
dataset. Can you think of any alternative models that would perhaps be
more appropriate for this dataset? (4 points). It is not really
appropriate to assume the population growth follows the linear model
because in reality, the growth rate of the population is affected by the
events happening to the world at various time points. Since we can see
from the actual trend that the slope before the 1940s is smaller and yet
the slope after that gets larger, I would fit a piecewise linear model
instead. I guess that increase of slope is due to baby boom after WW2?

\#4 Download the google trends time series dataset for the query yahoo.
This should be a monthly time series dataset that indicates the search
popularity of this query from January 2004 to August 2022. The goal of
this exercise is to fit the polynomial trend model
\[Y_i = \beta_0 + \beta_1 t_i + \cdots + \beta_k t_i^k + Z_i\] with
\(Z_i\) iid \(\sim N(0, \sigma^2)\) to this data set for an appropriate
value of k \(\leq\) 5. \#\#a Visually evaluate the fit of the least
squares estimate for this model to the observed data to pick an
appropriate value of k ≤ 5. Explain the reason for your choice of k. (4
points).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yahoo }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}yahoo.csv\textquotesingle{}}\NormalTok{, }\AttributeTok{header=}\NormalTok{T, }\AttributeTok{skip=}\DecValTok{1}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(yahoo) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Month\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}y\textquotesingle{}}\NormalTok{)}
\NormalTok{yahoo }\OtherTok{\textless{}{-}}\NormalTok{ yahoo[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(yahoo)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{), ] }\CommentTok{\# drop last row, which corresponds to Sep 2022}
\CommentTok{\#yahoo.ts \textless{}{-} ts(yahoo$y, start = c(2004, 1), end = c(2022, 8), frequency = 12)}
\FunctionTok{head}\NormalTok{(yahoo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Month  y
## 1 2004-01 40
## 2 2004-02 40
## 3 2004-03 40
## 4 2004-04 40
## 5 2004-05 42
## 6 2004-06 48
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{=} \FunctionTok{length}\NormalTok{(yahoo}\SpecialCharTok{$}\NormalTok{y) }\CommentTok{\# number of timepoints}
\end{Highlighting}
\end{Shaded}

By looking at the plot of the yahoo trend data, I decided not to use a
linear model because the data has a clear trend of going up and then
going down.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\NormalTok{n}
\FunctionTok{plot}\NormalTok{(t, yahoo}\SpecialCharTok{$}\NormalTok{y, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-16-1.pdf}

Thus, let's try k from 2. k=2:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(t, yahoo}\SpecialCharTok{$}\NormalTok{y, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{)}
\NormalTok{lin }\OtherTok{=} \FunctionTok{lm}\NormalTok{(yahoo}\SpecialCharTok{$}\NormalTok{y }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ t }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\FunctionTok{lines}\NormalTok{(t, lin}\SpecialCharTok{$}\NormalTok{fitted.values, }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-17-1.pdf} k =
3:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(t, yahoo}\SpecialCharTok{$}\NormalTok{y, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{)}
\NormalTok{lin }\OtherTok{=} \FunctionTok{lm}\NormalTok{(yahoo}\SpecialCharTok{$}\NormalTok{y }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ t }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{3}\NormalTok{))}
\FunctionTok{lines}\NormalTok{(t, lin}\SpecialCharTok{$}\NormalTok{fitted.values, }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-18-1.pdf} k =
4:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(t, yahoo}\SpecialCharTok{$}\NormalTok{y, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{)}
\NormalTok{lin }\OtherTok{=} \FunctionTok{lm}\NormalTok{(yahoo}\SpecialCharTok{$}\NormalTok{y }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ t }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{3}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{4}\NormalTok{))}
\FunctionTok{lines}\NormalTok{(t, lin}\SpecialCharTok{$}\NormalTok{fitted.values, }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-19-1.pdf} k =
5:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(t, yahoo}\SpecialCharTok{$}\NormalTok{y, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{)}
\NormalTok{lin }\OtherTok{=} \FunctionTok{lm}\NormalTok{(yahoo}\SpecialCharTok{$}\NormalTok{y }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ t }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{3}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{4}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{5}\NormalTok{))}
\FunctionTok{lines}\NormalTok{(t, lin}\SpecialCharTok{$}\NormalTok{fitted.values, }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-20-1.pdf} I
would choose k = 5 because it successfully captures the decreasing trend
in the ending part of the data. k = 3 is the second best, but the
polynomial goes up at the end, which the actual trend is still going
down. Besides, k = 5 overall fits the data better. \textbackslash{}
Update: it turns out if I choose k = 5, R will not be able to invert the
matrix \((X'X)\) because its entries, which involve numbers being raised
to the k\^{}th power, are too large. After reading the GSI's response on
Ed, I learned that k = 3 will be better. It is the second best fit among
the plots above and it is less vulnerable to overfitting. After all, a
model with a trend of a high-degree polynomial will not do well on
forecasting - the model will soar to infinity very fast, while our
common sense tells us that the trend should remain bounded for a long
period of time. So, we will use k = 3 from now on.

\hypertarget{b}{%
\subsection{b}\label{b}}

On a plot of the observed dataset, plot the polynomial corresponding to
the least squares estimate for the model with your chosen value of k. On
the same figure, plot polynomials corresponding to 30 samples from the
posterior distribution of the coefficients. Comment on the range of
uncertainty revealed in this plot. (5 points)

The posterior \(\vec\beta = (\beta_0, ..., \beta_3)^T\) conditioned on
data \(\vec y\) follows
\[t_{n-4}\big(\hat\beta, \; \frac{S(\hat\beta)}{n-4}(X'X)^{-1}\big),\]
where X is now \[\begin{bmatrix}
1 & t_1 & t_1^2 & t_1^3 \\
1 & t_2 & t_2^2 &  t_2^3 \\
\vdots & \vdots & \vdots & \vdots \\
1 & t_n & t_n^2 & t_n^3
\end{bmatrix}\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lin }\OtherTok{=} \FunctionTok{lm}\NormalTok{(yahoo}\SpecialCharTok{$}\NormalTok{y }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ t }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{3}\NormalTok{))}

\NormalTok{beta\_hat }\OtherTok{=} \FunctionTok{as.vector}\NormalTok{(lin}\SpecialCharTok{$}\NormalTok{coefficients)}
\NormalTok{S }\OtherTok{=} \FunctionTok{sum}\NormalTok{(lin}\SpecialCharTok{$}\NormalTok{residuals}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\CommentTok{\# residual sum of squares}
\NormalTok{X }\OtherTok{=} \FunctionTok{model.matrix}\NormalTok{(lin)}
\NormalTok{Sigma }\OtherTok{=}\NormalTok{ S }\SpecialCharTok{/}\NormalTok{ (n}\DecValTok{{-}4}\NormalTok{) }\SpecialCharTok{*} \FunctionTok{solve}\NormalTok{(}\FunctionTok{t}\NormalTok{(X) }\SpecialCharTok{\%*\%}\NormalTok{ X)}
\end{Highlighting}
\end{Shaded}

In the following plot, the red polynomial curve corresponds to the least
square estimate, whereas the other 30 pink curves are polynomials whose
coefficients are sampled from the posterior distribution.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(t, yahoo}\SpecialCharTok{$}\NormalTok{y, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{)}
\NormalTok{beta\_samples }\OtherTok{\textless{}{-}} \FunctionTok{get\_random\_t}\NormalTok{(}\AttributeTok{N=}\DecValTok{30}\NormalTok{, }\AttributeTok{mu=}\NormalTok{beta\_hat, }\AttributeTok{Sigma=}\NormalTok{Sigma, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}4}\NormalTok{)}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{30}\NormalTok{) \{}
\NormalTok{  y\_model }\OtherTok{=} \FunctionTok{lapply}\NormalTok{(t, }\ControlFlowTok{function}\NormalTok{(x) \{}
    \FunctionTok{sum}\NormalTok{(beta\_samples[i, ] }\SpecialCharTok{*} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, x, x}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{, x}\SpecialCharTok{\^{}}\DecValTok{3}\NormalTok{))}
\NormalTok{  \})}
  \FunctionTok{lines}\NormalTok{(t, y\_model, }\AttributeTok{col=}\StringTok{\textquotesingle{}pink\textquotesingle{}}\NormalTok{)}
\NormalTok{\}}
\FunctionTok{lines}\NormalTok{(t, lin}\SpecialCharTok{$}\NormalTok{fitted.values, }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-23-1.pdf} The
range of uncertainty is still pretty tight. The reason is the same as in
3b. We can calculate the 95\% confidence intervals for
\(\beta_0, ..., \beta_3\) as follows:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{c}\NormalTok{(beta\_hat[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(Sigma[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{]), beta\_hat[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(Sigma[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19.86559 26.64604
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{c}\NormalTok{(beta\_hat[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(Sigma[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]), beta\_hat[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(Sigma[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.098874 2.359273
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{c}\NormalTok{(beta\_hat[}\DecValTok{3}\NormalTok{] }\SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(Sigma[}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{]), beta\_hat[}\DecValTok{3}\NormalTok{] }\SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(Sigma[}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.02277641 -0.02009033
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{c}\NormalTok{(beta\_hat[}\DecValTok{4}\NormalTok{] }\SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(Sigma[}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{]), beta\_hat[}\DecValTok{4}\NormalTok{] }\SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(Sigma[}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.793732e-05 5.578575e-05
\end{verbatim}

We see that except for the CI for \(\beta_0\), the other CIs are pretty
tight. The intercept is allowed to change more because it only shifts
the model curve vertically, but changing other betas may change the
shape of the curve dramatically, so their range of uncertainty must be
small.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Plot the residuals obtained after fitting your model. Also plot the
  correlogram of the residuals. Is Gaussian White Noise suitable as a
  model for the residuals? (4 points)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(t, lin}\SpecialCharTok{$}\NormalTok{residuals, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-25-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{acf}\NormalTok{(lin}\SpecialCharTok{$}\NormalTok{residuals)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-25-2.pdf}
Since the acf has a visible decreasing pattern and many acfs are above
the blue threshold, Gaussian White Noise is not suitable as a model for
the residuals. Otherwise, the autocorrelations should be approximately
iid normal and so should not have a visible trend (also, I believe most
acfs will lie within the blue thresholds if the residuals were to follow
a Gaussian White Noise model).

\hypertarget{section}{%
\section{5}\label{section}}

Download the google trends time series dataset for the query frisbee.
This should be a monthly time series dataset that indicates the search
popularity of this query from January 2004 to August 2022. \#\# a
Describe a model that is appropriate for estimating the trend in this
dataset. Explain how you arrived at your model. (4 points)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fris }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}frisbee.csv\textquotesingle{}}\NormalTok{, }\AttributeTok{header=}\NormalTok{T, }\AttributeTok{skip=}\DecValTok{1}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(fris) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Month\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}y\textquotesingle{}}\NormalTok{)}
\NormalTok{fris }\OtherTok{\textless{}{-}}\NormalTok{ fris[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(fris)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{), ] }\CommentTok{\# drop last row, which corresponds to Sep 2022}
\FunctionTok{head}\NormalTok{(fris)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Month   y
## 1 2004-01  43
## 2 2004-02  53
## 3 2004-03  68
## 4 2004-04  92
## 5 2004-05 100
## 6 2004-06  83
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{=} \FunctionTok{length}\NormalTok{(fris}\SpecialCharTok{$}\NormalTok{y) }\CommentTok{\# number of timepoints}

\NormalTok{fris.ts }\OtherTok{\textless{}{-}} \FunctionTok{ts}\NormalTok{(fris}\SpecialCharTok{$}\NormalTok{y, }\AttributeTok{start =} \FunctionTok{c}\NormalTok{(}\DecValTok{2004}\NormalTok{, }\DecValTok{1}\NormalTok{), }\AttributeTok{end =} \FunctionTok{c}\NormalTok{(}\DecValTok{2022}\NormalTok{, }\DecValTok{8}\NormalTok{), }\AttributeTok{frequency =} \DecValTok{12}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

If we plot the frisbee time series, we can already see a strong seasonal
oscillation and guess that the period of the oscillation is a year. This
guess can be supported from the acf plot. The peaks of autocorrelation
at lag k occur when k is a multiple of 12, which suggests that the data
points versus those that shift 12 months ahead are in phase and so 12 is
likely to be the period.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\NormalTok{n}
\CommentTok{\#plot(t, fris$y, type=\textquotesingle{}l\textquotesingle{})}
\FunctionTok{plot}\NormalTok{(fris.ts)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-27-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{acf}\NormalTok{(fris}\SpecialCharTok{$}\NormalTok{y, }\AttributeTok{lag.max=}\DecValTok{30}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-27-2.pdf}
Thus, I will use the following model to fit the time series:
\[y_i = \beta_0 + \beta_1 t_i + \beta_2 t_i^2 + \beta_3 \cos(2\pi t_i/12) + \beta_4 \sin(2\pi t_i/12) + z_i,\]
where the \(z_i\)'s are iid following \(N(0, \sigma^2)\). The quadratic
part \(\beta_0 + \beta_1 t_i + \beta_2 t_i^2\) models the long-term
trend, while the cos and sin model the oscillation.

\hypertarget{b-1}{%
\subsection{b}\label{b-1}}

Estimate the trend in this dataset by fitting your model. Quantify the
uncertainty in your trend estimation. Explain your methodology briefly
(5 points).

Since the model is linear in the parameters, use linear regression to
get the least square estimate of \(\vec\beta\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\NormalTok{n}
\NormalTok{c }\OtherTok{\textless{}{-}} \FunctionTok{cos}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{/}\DecValTok{12}\SpecialCharTok{*}\NormalTok{t)}
\NormalTok{s }\OtherTok{\textless{}{-}} \FunctionTok{sin}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{/}\DecValTok{12}\SpecialCharTok{*}\NormalTok{t)}
\NormalTok{my.model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(fris}\SpecialCharTok{$}\NormalTok{y }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ t }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(t}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\SpecialCharTok{+}\NormalTok{ c }\SpecialCharTok{+}\NormalTok{ s)}
\FunctionTok{summary}\NormalTok{(my.model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = fris$y ~ 1 + t + I(t^2) + c + s)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -14.4417  -3.9410   0.1282   3.3420  22.9847 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  6.787e+01  1.208e+00  56.165  < 2e-16 ***
## t           -3.390e-01  2.480e-02 -13.667  < 2e-16 ***
## I(t^2)       7.121e-04  1.068e-04   6.670 2.06e-10 ***
## c           -1.316e+01  5.645e-01 -23.315  < 2e-16 ***
## s           -1.148e+00  5.645e-01  -2.034   0.0432 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.969 on 219 degrees of freedom
## Multiple R-squared:  0.8664, Adjusted R-squared:  0.864 
## F-statistic: 355.1 on 4 and 219 DF,  p-value: < 2.2e-16
\end{verbatim}

The posterior \(\vec\beta = (\beta_0, ..., \beta_4)^\text{T}\)
conditioned on data \(\vec y\) follows
\[t_{n-5}\big(\hat\beta, \; \frac{S(\hat\beta)}{n-5}(X'X)^{-1}\big),\]
where X is \[\begin{bmatrix}
1 & t_1 & t_1^2 & \cos(2\pi t_1/12) & \sin(2\pi t_1/12) \\
\vdots & \vdots & \vdots & \vdots & \vdots \\
1 & t_n & t_n^2 & \cos(2\pi t_n/12) & \sin(2\pi t_n/12)
\end{bmatrix}\]

Thus, each \(\beta_i\) follows
\(t_{n-5}\big(\hat\beta_i, \; \frac{S(\hat\beta)}{n-5}((X'X)^{-1})_{ii}\big)\),
and we can get a 95\% confidence interval for it from this t
distribution.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bhat }\OtherTok{=} \FunctionTok{as.vector}\NormalTok{(my.model}\SpecialCharTok{$}\NormalTok{coefficients)}
\NormalTok{S }\OtherTok{=} \FunctionTok{sum}\NormalTok{(my.model}\SpecialCharTok{$}\NormalTok{residuals}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\CommentTok{\# residual sum of squares}
\NormalTok{X }\OtherTok{=} \FunctionTok{model.matrix}\NormalTok{(my.model)}
\NormalTok{Sigma }\OtherTok{=}\NormalTok{ S }\SpecialCharTok{/}\NormalTok{ (n}\DecValTok{{-}5}\NormalTok{) }\SpecialCharTok{*} \FunctionTok{solve}\NormalTok{(}\FunctionTok{t}\NormalTok{(X) }\SpecialCharTok{\%*\%}\NormalTok{ X)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{) \{}
\NormalTok{  conf\_int }\OtherTok{=} \FunctionTok{c}\NormalTok{(bhat[i] }\SpecialCharTok{+} \FunctionTok{sqrt}\NormalTok{(Sigma[i,i])}\SpecialCharTok{*}\FunctionTok{qt}\NormalTok{(}\AttributeTok{p=}\NormalTok{.}\DecValTok{025}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}5}\NormalTok{), bhat[i] }\SpecialCharTok{+} \FunctionTok{sqrt}\NormalTok{(Sigma[i,i])}\SpecialCharTok{*}\FunctionTok{qt}\NormalTok{(}\AttributeTok{p=}\NormalTok{.}\DecValTok{975}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}5}\NormalTok{))}
  \FunctionTok{print}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{\textquotesingle{}CI for beta hat \%i: (\%f, \%f)\textquotesingle{}}\NormalTok{, i}\DecValTok{{-}1}\NormalTok{, conf\_int[}\DecValTok{1}\NormalTok{], conf\_int[}\DecValTok{2}\NormalTok{]))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "CI for beta hat 0: (65.487151, 70.250264)"
## [1] "CI for beta hat 1: (-0.387837, -0.290080)"
## [1] "CI for beta hat 2: (0.000502, 0.000923)"
## [1] "CI for beta hat 3: (-14.273440, -12.048425)"
## [1] "CI for beta hat 4: (-2.260693, -0.035678)"
\end{verbatim}

\#\#c Plot the residuals obtained after fitting your model. Also plot
the correlogram of the residuals. Is Gaussian White Noise suitable as a
model for the residuals? (4 points)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(t, my.model}\SpecialCharTok{$}\NormalTok{residuals, }\AttributeTok{type=}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\AttributeTok{main=}\StringTok{\textquotesingle{}Residuals\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-34-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{acf}\NormalTok{(my.model}\SpecialCharTok{$}\NormalTok{residuals, }\AttributeTok{lag.max=}\DecValTok{30}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1code_files/figure-latex/unnamed-chunk-34-2.pdf} No,
Gaussian White Noise is still not a suitable model for the residuals, as
there are still peaks at multiples of 12 and smaller ones at multiples
of 6. Adding \(\cos(2\pi m t_i/12)\) and \(\sin(2\pi m t_i/12)\) into
the model, where \(m = 2,3,4, ...\), may help cancel out the peaks.
After all, the shape of the oscillation graph need not look perfectly
sinusoidal, and it is known that any continuous periodic function can be
approximated by many sinusoids of the form \(\cos(2\pi m t_i/12)\) and
\(\sin(2\pi m t_i/12)\).

\end{document}
